# Generated by Django 5.1.4 on 2025-01-14 15:56

from django.db import migrations, models


def populate_states(apps, schema_editor):
    States = apps.get_model('collegeList', 'States')
    state_choices = [
        ('12', 'Arunachal Pradesh'),
        ('02', 'Himachal Pradesh'),
        ('23', 'Madhya Pradesh'),
        ('27', 'Maharashtra'),
        ('34', 'Puducherry'),
        ('09', 'Uttar Pradesh'),
        ('22', 'Chhattisgarh'),
        ('20', 'Jharkhand'),
        ('17', 'Meghalaya'),
        ('03', 'Punjab'),
        ('16', 'Tripura'),
        ('10', 'Bihar'),
        ('07', 'Delhi'),
        ('32', 'Kerala'),
        ('11', 'Sikkim'),
        ('38', 'The Dadra And Nagar Haveli And Daman And Diu'),
        ('05', 'Uttarakhand'),
        ('35', 'Andaman And Nicobar Islands'),
        ('28', 'Andhra Pradesh'),
        ('18', 'Assam'),
        ('04', 'Chandigarh'),
        ('06', 'Haryana'),
        ('01', 'Jammu And Kashmir'),
        ('37', 'Ladakh'),
        ('15', 'Mizoram'),
        ('21', 'Odisha'),
        ('36', 'Telangana'),
        ('30', 'Goa'),
        ('24', 'Gujarat'),
        ('29', 'Karnataka'),
        ('31', 'Lakshadweep'),
        ('14', 'Manipur'),
        ('13', 'Nagaland'),
        ('08', 'Rajasthan'),
        ('33', 'Tamil Nadu'),
        ('19', 'West Bengal'),
    ]
    for code, name in state_choices:
        States.objects.create(code=code, name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('collegeList', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('code', models.CharField(blank=True, max_length=2, null=True, unique=True)),
            ],
        ),
        migrations.RunPython(populate_states),
    ]
